name: 获取各插件最新版本号
on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"
jobs:
  build:
    name: 获取各插件最新版本号
    runs-on: ubuntu-latest
    steps:
    - name: 获取各插件最新版本号
      run: |
        echo qBittorrent $(curl -skL "https://api.github.com/repos/c0re100/qBittorrent-Enhanced-Edition/releases/latest" | grep tag_name | cut -f4 -d '"'  | sed 's/^[^v].*[^.0-9]/v/') >> Versions
        echo Alist $(curl -skL "https://api.github.com/repos/AlistGo/alist/releases/latest" | grep tag_name | cut -f4 -d '"'  | sed 's/^[^v].*[^.0-9]/v/') >> Versions
        echo AdGuardHome $(curl -skL "https://api.github.com/repos/AdGuardTeam/AdGuardHome/releases?per_page=1&page=0" | grep tag_name | cut -f4 -d '"'  | sed 's/^[^v].*[^.0-9]/v/') >> Versions
        echo zerotier $(curl -skL "https://api.github.com/repos/xilaochengv/ZeroTierOne/releases/latest" | grep tag_name | cut -f4 -d '"'  | sed 's/^[^v].*[^.0-9]/v/') >> Versions
        echo "各插件最新版本号获取时间：$(date '+%F %T')" > body
    - name: 上传到Release
      uses: softprops/action-gh-release@v1
      with:
          files: Versions
          tag_name: Latest
          body_path: body
